import type { Metadata } from "next";
import { Geist, Geist_Mono, Archivo} from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import logo from "@/images/logo-neutral-850.svg";
import logo100 from "@/images/logo-zinc-100.svg";
import CanvasBackground from "@/app/components/CanvasBackground";
import LoadBar from "@/app/components/LoadBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivo = Archivo({
  variable: "--font-archivo",
  display: 'swap',
  subsets: ["latin"]
});


export const metadata: Metadata = {
  title: "Pablo Nicolás | Fullstack Web Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  return (
    <html lang="en">
      <body className={`${archivo.variable} ${geistMono.variable} ${geistSans.variable} relative font-archivo antialiased cursor-default`}>
        { false && //I'll disable it for now because I found it annoying
        <div className="pointer-events-none bg-transparent w-full h-screen absolute hidden md:block">
            <CanvasBackground/>
        </div>
        }
        <div className={`bg-transparent md:bg-primary-950 bg-gradient-to-br from-primary-950 to-primary-900 min-h-screen text-primary-100 xl:py-16`}>
          <div className="z-10 bg-primary-900/30 border border-primary-500/20 relative flex flex-col xl:container m-auto w-full 2xl:w-2/3 h-screen xl:h-[80vh] max-h-screen xl:max-h-[80vh] md:rounded-lg overflow-hidden">
            <div className="w-full p-4 md:px-8 border-b border-primary-600/30 hidden md:flex items-center gap-x-2">
              <img src={logo100.src} className="w-5 h-5"/>
              <p className="font-semibold text-xs">Pablo Nicolás | <span className="font-light">Fullstack Web Developer</span></p>
            </div>
            <div className="w-full relative flex flex-col md:flex-row overflow-hidden">
              <Navbar/>
              <div className="relative overflow-y-scroll w-full p-4 md:p-6" style={{
                backgroundImage: `url(${logo.src})`,
                backgroundSize: `200px, 200px`,
                backgroundPosition: `calc(100% - 16px) calc(100% - 16px)`,
                backgroundRepeat: `no-repeat`
                }}>
                <>
                  {children}
                </>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
